# Generated by Django 4.2.5 on 2023-09-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarazModel',
            fields=[
                ('sn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Item', max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
